// AUTO-GENERATED by the nocms scaffold. Edit only if you intend the change
// to be permanent — re-scaffolding regenerates this file.

/**
 * The SiteLink corp credential UUID. Read from NEXT_PUBLIC_SITELINK_CREDENTIAL_ID
 * at build time. Sent as the X-Credential-ID header on every connector call.
 */
export const SITELINK_COMPANY_ID = (process.env.NEXT_PUBLIC_SITELINK_CREDENTIAL_ID ?? "").trim();

/**
 * Base URL for the GLI integration platform SiteLink connector. Set via
 * NEXT_PUBLIC_SITELINK_API_BASE in .env.local (dev) or Cloudflare Pages env
 * vars (prod). Falls back to the local dev port so the funnel works during
 * `bun run dev`.
 */
export function getSitelinkApiBase(): string {
  const base = process.env.NEXT_PUBLIC_SITELINK_API_BASE || "http://localhost:8345";
  return base.replace(/\/$/, "");
}

// NOTE: `process.env.NEXT_PUBLIC_*` below is direct property access on
// purpose — Next.js / webpack only inlines NEXT_PUBLIC_* vars when accessed
// by literal property name (`process.env.FOO`). Dynamic access like
// `process.env[name]` is NOT inlined and resolves to undefined in the
// browser bundle.
function requireValue(name: string, value: string | undefined): string {
  const v = (value ?? "").trim();
  if (!v) throw new Error(name + " is not set in the build env.");
  return v;
}

export function getOrganizationId(): string {
  return requireValue("NEXT_PUBLIC_GLI_ORGANIZATION_ID", process.env.NEXT_PUBLIC_GLI_ORGANIZATION_ID);
}

/**
 * POST {base}/{method} with the two tenancy headers (X-Organization-ID
 * + X-Credential-ID) and a JSON body. Mutating calls require an
 * Idempotency-Key — pass it via opts.
 *
 * Auth is bypassed on the dev connector (BYPASS_AUTH=true), so no
 * Authorization header is sent. Re-add bearer-token plumbing before
 * enabling auth.
 */
export async function callSitelink<TReq, TRes>(
  method: string,
  body: TReq,
  opts?: { idempotencyKey?: string },
): Promise<TRes> {
  if (!SITELINK_COMPANY_ID) {
    throw new Error("NEXT_PUBLIC_SITELINK_CREDENTIAL_ID is not set in the build env.");
  }
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    Accept: "application/json",
    "X-Organization-ID": getOrganizationId(),
    "X-Credential-ID": SITELINK_COMPANY_ID,
  };
  if (opts?.idempotencyKey) headers["Idempotency-Key"] = opts.idempotencyKey;

  const res = await fetch(getSitelinkApiBase() + "/" + method, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error("SiteLink " + method + " failed: HTTP " + res.status + (text ? " — " + text : ""));
  }
  return (await res.json()) as TRes;
}
